# nixpacks.toml

[build]
  commands = [
    "npm install --prefix server",    # Install server dependencies
    "npm run build --prefix client"    # Build the React client
  ]

[serve]
  command = "npm start --prefix server"  # Start the server
